[package]
name = "TransJLC"
version = "0.2.0"
authors = ["HalfSweet <HalfSweet@HalfSweet.cn>"]
edition = "2021"
repository = "https://github.com/HalfSweet/TransJLC"

license = "MIT"
description = "TransJLC is a tool for converting Gerber files from other EDAs to JLCEDA style"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.16" }
lazy_static = "1.5.0"
locale_config = "0.3.0"
regex = "1.10.4"
rust-embed = { version = "8.4.0", features = ["debug-embed"] }
rust-i18n = "3.1.1"
whoami = "1.5.1"
zip = "2.1.6"
colored = "2.1.0"
md-5 = "0.10.5"
rand = "0.8.5"
tempfile = "3.8.1"
